"""Metadata structure retrieved for image files using exif tool command for cameras
exiftool -json -g -c '%.6f' *.jpg > makernotes.json
"""

# KEYS
FUJI = "FUJI"
LEICA = "LEICA_DLUX"
GENERIC = "GENERIC"
# Segment keys
SOURCE_FILE = "SourceFile"
EXIFTOOL = "ExifTool"
FILE = "File"
EXIF = "EXIF"
FLASHPIX = "FlashPix"
MAKERNOTES = "MakerNotes"
PRINTIM = "PrintIM"
XMP = "XMP"
MPF = "MPF"
COMPOSITE = "Composite"

# Parameters to be copied into keywords field
EXIF_META_SELECTED = {
    FUJI: {
        MAKERNOTES: [
            "FilmMode",
            "GrainEffectRoughness",
            "GrainEffectSize",
            "ColorChromeEffect",
            "ColorChromeFXBlue",
            "InternalSerialNumber",
            "NoiseReduction",
            "FocusPixel",
            "FujiModel",
            "FujiModel2",
            "RollAngle",
        ]
    },
    LEICA: {
        MAKERNOTES: [
            "PhotoStyle",
            "FilterEffect",
            "MonochromeFilterEffect",
            "MonochromeGrainEffect",
            "MacroMode",
            "ColorTempKelvin",
            "RollAngle",
            "PitchAngle",
        ]
    },
    # NOTE NOT ALL GENERIC VALUES MIGHT BE EXISTING IN EXIF DATA FOR DIFFERENT CAMERAS
    GENERIC: {
        FILE: [
            "FileName",
            "Directory",
            "FileSize",
            "FileModifyDate",
            "FileAccessDate",
            "FileCreateDate",
            "ImageWidth",
            "ImageHeight",
        ],
        EXIF: [
            "ApertureValue",
            "FNumber",
            "ISO",
            "ExposureTime",
            "ExposureCompensation",
            "BrightnessValue",
            "FocalLength",
            "WhiteBalance",
            "Make",
            "Model",
            "LensMake",
            "LensModel",
            "LensInfo",
            "LensSerialNumber",
            "MaxApertureValue",
            "SerialNumber",
            "Software",
            "DateTimeOriginal",
            "CreateDate",
            "ModifyDate",
            "OffsetTime",
        ],
        COMPOSITE: [
            "Aperture",
            "ShutterSpeed",
            "ImageSize",
            "Megapixels",
            "ScaleFactor35efl",
            "CircleOfConfusion",
            "FOV",
            "FocalLength35efl",
            "HyperfocalDistance",
            "LightValue",
            "SubSecCreateDate",
            "SubSecDateTimeOriginal",
            "SubSecModifyDate",
        ],
    },
}

EXIF_META_ALL = {
    FUJI: {
        SOURCE_FILE: [],
        EXIFTOOL: ["ExifToolVersion"],
        FILE: [
            "FileName",
            "Directory",
            "FileSize",
            "FileModifyDate",
            "FileAccessDate",
            "FileCreateDate",
            "FilePermissions",
            "FileType",
            "FileTypeExtension",
            "MIMEType",
            "ExifByteOrder",
            "ImageWidth",
            "ImageHeight",
            "EncodingProcess",
            "BitsPerSample",
            "ColorComponents",
            "YCbCrSubSampling",
        ],
        EXIF: [
            "Make",
            "Model",
            "Orientation",
            "XResolution",
            "YResolution",
            "ResolutionUnit",
            "Software",
            "ModifyDate",
            "Artist",
            "YCbCrPositioning",
            "Copyright",
            "ExposureTime",
            "FNumber",
            "ExposureProgram",
            "ISO",
            "SensitivityType",
            "ExifVersion",
            "DateTimeOriginal",
            "CreateDate",
            "OffsetTime",
            "OffsetTimeOriginal",
            "OffsetTimeDigitized",
            "ComponentsConfiguration",
            "CompressedBitsPerPixel",
            "ShutterSpeedValue",
            "ApertureValue",
            "BrightnessValue",
            "ExposureCompensation",
            "MaxApertureValue",
            "MeteringMode",
            "LightSource",
            "Flash",
            "FocalLength",
            "UserComment",
            "SubSecTime",
            "SubSecTimeOriginal",
            "SubSecTimeDigitized",
            "CameraElevationAngle",
            "FlashpixVersion",
            "ColorSpace",
            "ExifImageWidth",
            "ExifImageHeight",
            "InteropIndex",
            "InteropVersion",
            "FocalPlaneXResolution",
            "FocalPlaneYResolution",
            "FocalPlaneResolutionUnit",
            "SensingMethod",
            "FileSource",
            "SceneType",
            "CustomRendered",
            "ExposureMode",
            "WhiteBalance",
            "FocalLengthIn35mmFormat",
            "SceneCaptureType",
            "Sharpness",
            "SubjectDistanceRange",
            "SerialNumber",
            "LensInfo",
            "LensMake",
            "LensModel",
            "LensSerialNumber",
            "CompositeImage",
            "Compression",
            "ThumbnailOffset",
            "ThumbnailLength",
            "ThumbnailImage",
        ],
        MAKERNOTES: [
            "Version",
            "InternalSerialNumber",
            "Quality",
            "Sharpness",
            "WhiteBalance",
            "Saturation",
            "Contrast",
            "WhiteBalanceFineTune",
            "NoiseReduction",
            "Clarity",
            "FujiFlashMode",
            "FlashExposureComp",
            "FocusMode",
            "AFMode",
            "FocusPixel",
            "AF-SPriority",
            "AF-CPriority",
            "FocusMode2",
            "PreAF",
            "AFAreaMode",
            "AFAreaPointSize",
            "AFAreaZoneSize",
            "AF-CSetting",
            "AF-CTrackingSensitivity",
            "AF-CSpeedTrackingSensitivity",
            "AF-CZoneAreaSwitching",
            "SlowSync",
            "PictureMode",
            "ExposureCount",
            "ShadowTone",
            "HighlightTone",
            "LensModulationOptimizer",
            "GrainEffectRoughness",
            "ColorChromeEffect",
            "GrainEffectSize",
            "CropMode",
            "ColorChromeFXBlue",
            "ShutterType",
            "AutoBracketing",
            "SequenceNumber",
            "DriveMode",
            "DriveSpeed",
            "BlurWarning",
            "FocusWarning",
            "ExposureWarning",
            "DynamicRange",
            "FilmMode",
            "DynamicRangeSetting",
            "DevelopmentDynamicRange",
            "MinFocalLength",
            "MaxFocalLength",
            "MaxApertureAtMinFocal",
            "MaxApertureAtMaxFocal",
            "ImageStabilization",
            "ImageGeneration",
            "ImageCount",
            "FlickerReduction",
            "FujiModel",
            "FujiModel2",
            "RollAngle",
            "FacesDetected",
            "NumFaceElements",
        ],
        PRINTIM: ["PrintIMVersion"],
        XMP: ["Rating"],
        FLASHPIX: ["PreviewImageWidth", "PreviewImageHeight", "PreviewImage"],
        COMPOSITE: [
            "Aperture",
            "ImageSize",
            "Megapixels",
            "PreviewImageSize",
            "ScaleFactor35efl",
            "ShutterSpeed",
            "SubSecCreateDate",
            "SubSecDateTimeOriginal",
            "SubSecModifyDate",
            "CircleOfConfusion",
            "FOV",
            "FocalLength35efl",
            "HyperfocalDistance",
            "LightValue",
            "LensID",
        ],
    },
    LEICA: {
        SOURCE_FILE: [],
        EXIFTOOL: ["ExifToolVersion"],
        FILE: [
            "FileName",
            "Directory",
            "FileSize",
            "FileModifyDate",
            "FileAccessDate",
            "FileCreateDate",
            "FilePermissions",
            "FileType",
            "FileTypeExtension",
            "MIMEType",
            "ExifByteOrder",
            "ImageWidth",
            "ImageHeight",
            "EncodingProcess",
            "BitsPerSample",
            "ColorComponents",
            "YCbCrSubSampling",
        ],
        EXIF: [
            "Make",
            "Model",
            "Orientation",
            "XResolution",
            "YResolution",
            "ResolutionUnit",
            "Software",
            "ModifyDate",
            "YCbCrPositioning",
            "ExposureTime",
            "FNumber",
            "ExposureProgram",
            "ISO",
            "SensitivityType",
            "StandardOutputSensitivity",
            "ExifVersion",
            "DateTimeOriginal",
            "CreateDate",
            "OffsetTime",
            "OffsetTimeOriginal",
            "OffsetTimeDigitized",
            "ComponentsConfiguration",
            "CompressedBitsPerPixel",
            "ExposureCompensation",
            "MaxApertureValue",
            "MeteringMode",
            "LightSource",
            "Flash",
            "FocalLength",
            "SubSecTime",
            "SubSecTimeOriginal",
            "SubSecTimeDigitized",
            "FlashpixVersion",
            "ColorSpace",
            "ExifImageWidth",
            "ExifImageHeight",
            "InteropIndex",
            "InteropVersion",
            "SensingMethod",
            "FileSource",
            "SceneType",
            "CustomRendered",
            "ExposureMode",
            "WhiteBalance",
            "DigitalZoomRatio",
            "FocalLengthIn35mmFormat",
            "SceneCaptureType",
            "GainControl",
            "Contrast",
            "Saturation",
            "Sharpness",
            "LensInfo",
            "LensMake",
            "LensModel",
            "LensSerialNumber",
            "Compression",
            "ThumbnailOffset",
            "ThumbnailLength",
            "ThumbnailImage",
        ],
        MAKERNOTES: [
            "ImageQuality",
            "FirmwareVersion",
            "WhiteBalance",
            "FocusMode",
            "AFAreaMode",
            "ImageStabilization",
            "MacroMode",
            "ShootingMode",
            "Audio",
            "DataDump",
            "FlashBias",
            "InternalSerialNumber",
            "PanasonicExifVersion",
            "ColorEffect",
            "TimeSincePowerOn",
            "BurstMode",
            "SequenceNumber",
            "ContrastMode",
            "NoiseReduction",
            "SelfTimer",
            "Rotation",
            "AFAssistLamp",
            "OpticalZoomMode",
            "ConversionLens",
            "TravelDay",
            "BatteryLevel",
            "Contrast",
            "WorldTimeLocation",
            "AdvancedSceneType",
            "FacesDetected",
            "Saturation",
            "Sharpness",
            "JPEGQuality",
            "ColorTempKelvin",
            "BracketSettings",
            "WBShiftAB",
            "WBShiftGM",
            "FlashCurtain",
            "LongExposureNoiseReduction",
            "PanasonicImageWidth",
            "PanasonicImageHeight",
            "AFPointPosition",
            "NumFacePositions",
            "FacesRecognized",
            "Title",
            "BabyName",
            "Location",
            "Country",
            "State",
            "City",
            "Landmark",
            "IntelligentResolution",
            "MergedImages",
            "BurstSpeed",
            "IntelligentD-Range",
            "ClearRetouch",
            "City2",
            "PhotoStyle",
            "WBShiftIntelligentAuto",
            "AccelerometerZ",
            "AccelerometerX",
            "AccelerometerY",
            "CameraOrientation",
            "RollAngle",
            "PitchAngle",
            "WBShiftCreativeControl",
            "SweepPanoramaDirection",
            "SweepPanoramaFieldOfView",
            "TimerRecording",
            "InternalNDFilter",
            "HDR",
            "ShutterType",
            "FilterEffect",
            "ClearRetouchValue",
            "TouchAE",
            "MonochromeFilterEffect",
            "HighlightShadow",
            "TimeStamp",
            "VideoBurstResolution",
            "MultiExposure",
            "RedEyeRemoval",
            "VideoBurstMode",
            "DiffractionCorrection",
            "FocusBracket",
            "LongExposureNRUsed",
            "PostFocusMerging",
            "VideoPreburst",
            "SensorType",
            "MonochromeGrainEffect",
            "TimeLapseShotNumber",
            "MakerNoteVersion",
            "SceneMode",
            "HighlightWarning",
            "DarkFocusEnvironment",
            "WBRedLevel",
            "WBGreenLevel",
            "WBBlueLevel",
            "TextStamp",
            "BabyAge",
        ],
        PRINTIM: ["PrintIMVersion"],
        XMP: ["About", "Rating"],
        MPF: [
            "MPFVersion",
            "NumberOfImages",
            "MPImageFlags",
            "MPImageFormat",
            "MPImageType",
            "MPImageLength",
            "MPImageStart",
            "DependentImage1EntryNumber",
            "DependentImage2EntryNumber",
            "PreviewImage",
        ],
        COMPOSITE: [
            "Aperture",
            "BlueBalance",
            "ImageSize",
            "Megapixels",
            "RedBalance",
            "ScaleFactor35efl",
            "ShutterSpeed",
            "SubSecCreateDate",
            "SubSecDateTimeOriginal",
            "SubSecModifyDate",
            "AdvancedSceneMode",
            "CircleOfConfusion",
            "FOV",
            "FocalLength35efl",
            "HyperfocalDistance",
            "LightValue",
        ],
    },
}

# Example usage:
if __name__ == "__main__":
    pass
